# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
- jekyll-asciidoc
- jekyll-paginate

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
#relative_permalinks:	false

title: John Krug
tagline: ' - library analytics/systems, cycling'
description: 'Mostly to do with library analytics/systems and cycling. Maybe other stuff. <a href="/atom.xml">Atom</a>.'

url: https://john.libtics.org
baseurl: /
paginate: 10

# About/contact
author:
  name: John Krug
  url: https://john.libtics.org
  email: jhkrug@protonmail.com

theme: jekyll-theme-slate

excerpt_seperator: "<!--more-->"

asciidoc:
  excerpt_seperator: "\\ more"
  require_front_matter_header: true

asciidoctor: {}
