# Dependencies
markdown:            kramdown
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:         rb-pygments
gems: ["jekyll-paginate"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               John Krug
tagline:             ''
description:         'Some things to do with Library Systems and Analytics. And maybe bicycles and other things.'
url:                 http://jhkrug.gihub.io
baseurl:             /
paginate:            10

# About/contact
author:
  name:              John Krug
  url:               https://jhkrug.github.io
  email:             jhkrug@protonmail.com

# Custom vars
#version:             1.0.0

excerpt_separator: "\n\n"

