# Dependencies
markdown:	kramdown
highlighter: rouge
plugins: ["jekyll-paginate"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
#relative_permalinks:	false

title: John Krug
tagline: ' - library analytics/systems, cycling'
description: 'Mostly to do with library analytics/systems and cycling. Maybe other stuff.'
url: https://john.libtics.org
baseurl: /
paginate: 10
google_analytics: UA-55530748-1

# About/contact
author:
  name: John Krug
  url: https://john.libtics.org
  email: jhkrug@protonmail.com

excerpt_separator: "\n\n"

theme: jekyll-theme-slate

