# Dependencies
markdown:				kramdown
highlighter:			rouge
gems:					["jekyll-paginate"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:				pretty
relative_permalinks:	false

# Setup
title:					John Krug
tagline:				' - library systems and analytics'
description:			'Some things to do with Library Systems and Analytics. And maybe bicycles and other things.'
url:					https://jhkrug.gihub.io
baseurl:				/
paginate:				10

# About/contact
author:
  name:					John Krug
  url:					https://jhkrug.github.io
  email:				jhkrug@protonmail.com

excerpt_separator: "\n\n"

#theme: jekyll-theme-minimal