# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
- jekyll-paginate
- jekyll-remote-theme

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
#relative_permalinks:	false

title: John Krug
tagline: ' - tech writer, cycling'
description: 'Mostly to do with tech writing, SUSE, cloud infrastructure, open-source, library analytics/systems and cycling. Maybe other stuff. <a href="/atom.xml">Atom</a>.'

url: https://jhkrug.github.io
baseurl: /
paginate: 10

# About/contact
author:
  name: John Krug
  url: https://jhkrug.github.io
  email: jh.krug@gmail.com

theme: jekyll-theme-slate

excerpt_seperator: "<!--more-->"

asciidoc: {}
#asciidoc:
#  excerpt_seperator: "\\ more"
#  require_front_matter_header: true

asciidoctor: {}
